(() => {
  'use strict';

  const SUPPORTED_LANGUAGES = ['en', 'tr', 'de', 'es', 'fr'];

  const copy = {
    tr: {
      meta: {
        home: ['Morph Jam — Şekil değiştiren blok bulmacaları', 'Blokları kaydır, şekillerini değiştir ve her parçayı doğru kapıya ulaştır.'],
        support: ['Morph Jam Destek', 'Morph Jam yardım, sık sorulan sorular ve iletişim bilgileri.'],
        privacy: ['Morph Jam Gizlilik Politikası', 'Morph Jam mobil oyunu için Gizlilik Politikası.'],
        terms: ['Morph Jam Kullanım Koşulları', 'Morph Jam mobil oyunu için Kullanım Koşulları.'],
        deleteAccount: ['Morph Jam Hesabını Sil', 'Morph Jam misafir verilerini veya bağlı hesabını kalıcı olarak silme adımları.']
      },
      nav: { home: 'Ana sayfa', game: 'Oyun', screens: 'Ekranlar', support: 'Destek', privacy: 'Gizlilik', terms: 'Kullanım koşulları', deleteAccount: 'Hesabı sil' },
      home: {
        eyebrow: 'Şekil değiştiren blok mantık bulmacası',
        title: 'Kaydır. Dönüştür. <span class="accent">Çıkışı bul.</span>',
        lead: 'Bloklar yalnızca hareket etmez. Onları döndür, böl, uzat ve küçült; ardından her şekli doğru çıkışa ulaştır.',
        discover: 'Morph Jam’i keşfet', getSupport: 'Destek al', availability: 'Yakında iPhone ve Android’de',
        gameEyebrow: 'Kendini yeniden kuran bir bulmaca', gameTitle: 'Her hamle tahtayı değiştirebilir.',
        gameLead: 'Bir blok, önüne bir engel çıkana kadar kayar. Doğru durma noktası hem parçayı hem de kurduğun planı dönüştürebilir.',
        shapeTitle: 'Şekli değiştir', shapeBody: 'Parçaları kapılara uydurmak ve yeni yollar açmak için döndür, uzat veya küçült.',
        splitTitle: 'Parçayı böl', splitBody: 'Çift uzunluktaki bir parça, kendi rotası ve çıkışı olan iki ayrı probleme dönüşebilir.',
        stepTitle: 'Tek adımlık yardım al', stepBody: 'Takıldığında Yardım, mevcut tahtayı yeniden çözer ve bütün cevabı değil yalnızca güvenli bir hamleyi gösterir.',
        screensEyebrow: 'Oyunun içinden', screensTitle: 'Net kurallar. Beklenmedik sonuçlar.',
        screen1: 'Parçalar yalnızca hareket etmez; şekil değiştirir.', screen2: 'Bölme, tek parçayı iki ayrı sorumluluğa dönüştürür.', screen3: 'Her parça yerine oturana kadar uzat, küçült ve döndür.'
      },
      support: {
        eyebrow: 'Destek', title: 'Nasıl yardımcı olabiliriz?', lead: 'Temel bilgilere aşağıdan ulaşabilir veya bize e-posta gönderebilirsin.',
        emailTitle: 'E-posta desteği', detailsTitle: 'Yararlı bilgiler', detailsBody: 'Sorunu daha hızlı inceleyebilmemiz için cihazını, işletim sistemi sürümünü, uygulama sürümünü ve level numarasını ekle.',
        basicsTitle: 'Bulmaca nasıl çalışır?',
        basicsBody: '<li>Bir bloğu dört yönden birine kaydır. Duvar, engel veya başka bir blok durdurana kadar hareket eder.</li><li>Her bloğu aynı renkteki kapıdan geçir. Numaralı kapı yalnızca tam o boyutu, <strong>∞</strong> kapısı ise her boyutu kabul eder.</li><li>Döndürme, Bölme, Uzatma veya Küçültme karesi yalnızca blok hamlesini o karenin üzerinde bitirdiğinde etkinleşir.</li>',
        stuckTitle: 'Bir levelda takıldım', stuckBody: 'Oyundaki <strong>Yardım</strong> düğmesine dokun. Mevcut tahtayı kontrol eder ve güvenli bir yön hamlesi gösterir; çözümün tamamını açıklamaz. Son kararına dönmek için Geri Al özelliğini de kullanabilirsin.',
        purchasesTitle: 'Satın alımı geri yükleme', purchasesBody: 'Oyun içi Mağazayı aç ve <strong>Satın Alımları Geri Yükle</strong> seçeneğini kullan. Reklamları Kaldır gibi kalıcı satın alımlar Apple veya Google mağaza hesabına bağlıdır. Tüketilmiş coin paketleri geri yüklenemez.',
        progressTitle: 'İlerleme veya hesap sorunu', progressBody: 'Morph Jam misafir olarak oynanabilir. Desteklenen bir giriş sağlayıcısını bağladıysan eşitlenmiş ilerlemeyi geri almak için aynı sağlayıcıyı kullan. Yanlış ilerleme görünüyorsa etkilenen cihazda oynamayı bırak ve veri silmeden önce bizimle iletişime geç.',
        adsTitle: 'Reklam ve gizlilik tercihleri', adsBody: 'Mevcut reklam izinlerini <strong>Ayarlar → Reklam Tercihleri</strong> bölümünden inceleyebilir veya değiştirebilirsin. iOS takip izni, cihazın Ayarlar uygulamasından da değiştirilebilir.',
        reportTitle: 'Hata bildir', reportBody: '<a href="mailto:support@novacodedynamics.com?subject=Morph%20Jam%20Hata%20Bildirimi">support@novacodedynamics.com</a> adresine yaz. Beklediğin sonucu, yaşanan durumu ve yaptığın son işlemi açıkla. Ekran görüntüsü yardımcı olur; asla parola veya ödeme kartı bilgisi gönderme.',
        sideNav: '<strong>Bu sayfada</strong><a href="#basics">Bulmaca temelleri</a><a href="#stuck">Takıldım</a><a href="#purchases">Satın alımlar</a><a href="#progress">İlerleme</a><a href="#ads">Reklam tercihleri</a><a href="#report">Hata bildir</a>'
      },
      privacy: {
        eyebrow: 'Yasal', title: 'Gizlilik Politikası', lead: 'Yürürlük tarihi: 16 Ağustos 2026 · iOS ve Android için Morph Jam',
        intro: 'Bu Gizlilik Politikası, <strong>NovaCode Dynamics Inc.</strong> (“NovaCode Dynamics”, “biz”) olarak Morph Jam’i kullandığında bilgileri nasıl işlediğimizi açıklar. Sorularını veya gizlilik taleplerini <a href="mailto:support@novacodedynamics.com?subject=Morph%20Jam%20Gizlilik">support@novacodedynamics.com</a> adresine gönderebilirsin.',
        collectTitle: '1. İşlediğimiz bilgiler',
        collectBody: '<table><thead><tr><th>Kategori</th><th>Örnekler ve amaç</th></tr></thead><tbody><tr><td>Kurulum ve hesap tanımlayıcıları</td><td>Misafir kurulum kimliği ve giriş yapmayı seçersen Apple veya Google tarafından sağlanan tanımlayıcılar. Hesapları çalıştırmak ve ilerlemeyi eşitlemek için kullanılır.</td></tr><tr><td>Oyun ve kayıt verileri</td><td>Tamamlanan levellar, yıldızlar, coinler, ayarlar, yardım kullanımı ve benzeri ilerleme bilgileri. Oyunu kaydetmek, eşitlemek ve geliştirmek için kullanılır.</td></tr><tr><td>Satın alma bilgileri</td><td>Ürün, işlem, satın alma belirteci ve hak bilgileri. Satın alımları doğrulamak, mükerrer coin yüklemesini önlemek ve uygun ürünleri geri yüklemek için kullanılır. Ödeme kartı bilgilerini almayız.</td></tr><tr><td>Analitik ve tanılama</td><td>Uygulama sürümü, platform, oturum ve level olayları, tamamlama, yeniden başlatma, ipucu, geri alma, performans ve hata bilgileri. Güvenilirliği ve bulmaca zorluğunu anlamak için kullanılır.</td></tr><tr><td>Reklam ve izin verileri</td><td>Mevcut olduğunda reklam tanımlayıcıları, izin durumu, reklam istekleri ve etkileşimleri. Reklam sunmak, ölçmek ve sınırlamak için kullanılır. Kişiselleştirilmiş reklam yalnızca izin verilen ve onay verilen durumlarda kullanılır.</td></tr><tr><td>Destek iletişimleri</td><td>Yardım isterken gönderdiğin e-posta adresi ve diğer bilgiler.</td></tr></tbody></table><p>Kesin konum, kişiler, fotoğraflar, kamera veya mikrofon içeriği, sağlık verileri ya da ödeme kartı numarası istemeyiz.</p>',
        useTitle: '2. Bilgileri nasıl kullanırız?',
        useBody: '<ul><li>Oyunu, misafir erişimini, isteğe bağlı hesapları, bulut kaydını, desteği ve satın alma geri yüklemelerini sunmak.</li><li>Satın alımları doğrulamak, hizmeti güvenceye almak, dolandırıcılığı önlemek ve arızaları teşhis etmek.</li><li>Oyun performansını ölçmek; level dengesini, erişilebilirliği ve oyuncu deneyimini geliştirmek.</li><li>Geçerli izinler elverdiğinde kişiselleştirilmiş reklamlar dahil reklam sunmak ve ölçmek.</li><li>Yasal yükümlülükleri yerine getirmek ve geçerli hak taleplerini yanıtlamak.</li></ul>',
        basisTitle: '3. Hukuki dayanaklar', basisBody: 'GDPR, Birleşik Krallık GDPR’ı veya benzer yasaların geçerli olduğu durumlarda; talep edilen oyun ve hesap özelliklerini sunmak için sözleşmenin ifasına, hizmeti işletme, güvenceye alma ve geliştirme konusundaki meşru menfaatlerimize, gerektiğinde kişiselleştirilmiş reklam veya takip için rızaya ve geçerli yasal yükümlülüklere dayanırız. Rızanı oyun içindeki reklam tercihleri ve cihaz ayarları üzerinden geri çekebilirsin.',
        shareTitle: '4. Hizmet sağlayıcılar ve açıklama',
        shareBody: '<p>Morph Jam’i işletmemize yardımcı olan hizmet sağlayıcılarla bilgi işleyebiliriz:</p><ul><li>Uygulama dağıtımı, giriş, satın alma, izin araçları ve reklam hizmetleri için <strong>Apple</strong> ve <strong>Google</strong>.</li><li>Oyun analitiği için <strong>GameAnalytics</strong>.</li><li>Hesaplar, bulut kayıtları, level dağıtımı ve satın alma doğrulaması için <strong>Railway üzerinde barındırılan altyapı</strong> ve kendi yönettiğimiz Nakama hizmetleri.</li></ul><p>Bu sağlayıcılar verileri kendi koşulları ve gizlilik belgeleri kapsamında işler. Bilgileri ayrıca yasaların gerektirdiği durumlarda, kullanıcıları veya hizmeti korumak için ya da uygun güvencelere tabi bir ticari işlem kapsamında açıklayabiliriz.</p><p>Kişisel bilgileri para karşılığında satmayız. Bulunduğun yargı alanına göre kişiselleştirilmiş reklam, bağlamlar arası davranışsal reklamcılık amacıyla “paylaşım” sayılabilir; mevcut izin kontrolleri ve cihaz ayarları bunu sınırlamana olanak verir.</p>',
        retainTitle: '5. Saklama ve güvenlik', retainBody: 'Oyun hesabı ve bulut kayıt bilgileri genellikle hesap veya misafir profili etkin olduğu sürece tutulur ve hesap silme akışıyla silinir. Satın alma, güvenlik, destek ve analitik kayıtları; dolandırıcılığı önleme, yasal uyum, uyuşmazlık çözümü ve ilgili sağlayıcının belgelenmiş saklama uygulamaları için makul olarak gereken süre boyunca saklanabilir. Teknik ve kurumsal güvenlik önlemleri kullanırız; ancak hiçbir sistem mutlak güvenlik garanti edemez.',
        transferTitle: '6. Uluslararası aktarımlar', transferBody: 'Sağlayıcılarımız bilgileri bulunduğun ülkeden farklı ülkelerde işleyebilir. Gerektiğinde standart sözleşme maddeleri gibi tanınmış aktarım mekanizmalarına ve sağlayıcı güvencelerine dayanırız.',
        rightsTitle: '7. Tercihlerin ve hakların',
        rightsBody: '<ul><li>Üçüncü taraf giriş sağlayıcısı bağlamadan misafir olarak oynayabilirsin.</li><li>Mevcut reklam izinlerini <strong>Ayarlar → Reklam Tercihleri</strong> ve ilgili cihaz ayarlarından değiştirebilirsin.</li><li>Misafir verilerini veya hesabını <strong>Ayarlar → Hesap</strong> bölümünden silebilirsin. <a href="../delete-account/">Hesap silme rehberine</a> bak.</li><li>Yasaların tanıdığı durumlarda erişim, düzeltme, silme, taşınabilirlik, kısıtlama, itiraz veya rızayı geri çekme talebinde bulunabilirsin.</li></ul><p>Bir gizlilik hakkını kullanmak için <a href="mailto:support@novacodedynamics.com?subject=Morph%20Jam%20Gizlilik%20Talebi">support@novacodedynamics.com</a> adresine yaz. Talebin sana ait olduğunu doğrulamamız gerekebilir.</p>',
        childrenTitle: '8. Çocuklar', childrenBody: 'Morph Jam 13 yaşın altındaki çocuklara yönelik değildir ve 13 yaşın altındaki çocuklardan bilerek kişisel bilgi toplamayız. Bir çocuğun bilgi sağladığını düşünüyorsan, araştırıp gerektiğinde silebilmemiz için bizimle iletişime geç.',
        changesTitle: '9. Değişiklikler ve iletişim', changesBody: 'Morph Jam veya hizmet sağlayıcıları değiştikçe bu politikayı güncelleyebiliriz. Yukarıdaki yürürlük tarihi yenilenir ve önemli değişiklikler gerektiğinde bildirilir.',
        sideNav: '<strong>Bu sayfada</strong><a href="#collect">Bilgiler</a><a href="#use">Kullanım</a><a href="#basis">Hukuki dayanaklar</a><a href="#share">Sağlayıcılar</a><a href="#retain">Saklama</a><a href="#rights">Hakların</a><a href="#children">Çocuklar</a>'
      },
      terms: {
        eyebrow: 'Yasal', title: 'Kullanım Koşulları', lead: 'Yürürlük tarihi: 16 Ağustos 2026 · iOS ve Android için Morph Jam',
        intro: 'Bu Kullanım Koşulları (“Koşullar”), <strong>NovaCode Dynamics Inc.</strong> tarafından sunulan Morph Jam’i kullanımını düzenler. Morph Jam’i indirerek veya kullanarak bu Koşulları kabul edersin. Kabul etmiyorsan uygulamayı kullanma.',
        eligibilityTitle: '1. Uygunluk ve hesaplar', eligibilityBody: 'Bu Koşulları kabul etmeye yasal olarak yetkili olmalısın. Morph Jam 13 yaşın altındaki çocuklara yönelik değildir. Misafir olarak oynayabilirsin; desteklenen bir giriş sağlayıcısını bağlamak isteğe bağlıdır. Bağlı hesabın üzerinden yapılan işlemlerden ve cihazın ile sağlayıcı giriş bilgilerinin güvenliğinden sen sorumlusun.',
        licenseTitle: '2. Sınırlı lisans', licenseBody: 'Bu Koşullara ve uygulamayı edindiğin mağazanın kurallarına tabi olarak, Morph Jam’i ticari olmayan eğlence amacıyla kullanman için kişisel, sınırlı, münhasır olmayan, devredilemez ve geri alınabilir bir lisans veririz. Herhangi bir mülkiyet hakkı sana devredilmez.',
        purchasesTitle: '3. Sanal öğeler ve satın alımlar', purchasesBody: '<ul><li>Coinler ve diğer sanal öğelerin nakit değeri yoktur, paraya çevrilemez ve açıkça sunduğumuz özellikler dışında devredilemez.</li><li>Satın alımlar Apple veya Google tarafından kendi ödeme ve iade politikaları kapsamında işlenir. Ödeme kartı bilgilerini almayız.</li><li>Kalıcı satın alımlar, bunları alan mağaza hesabı üzerinden geri yüklenebilir. Tüketilebilir coin paketleri kullanıldıktan sonra geri yüklenemez.</li><li>Fiyatlar ve kullanılabilirlik mağaza, para birimi, vergi ve bölgeye göre değişebilir.</li></ul>',
        conductTitle: '4. Kabul edilebilir kullanım', conductBody: 'Morph Jam’i veya ilgili hizmetleri kötüye kullanamaz; diğer kullanıcıları ya da altyapıyı engelleyemez; yetkisiz erişim girişiminde bulunamaz; satın alma veya reklam sistemlerini istismar edemez; hizmetleri kötüye kullanmak için oynanışı otomatikleştiremez; değiştirilmiş kopyalar dağıtamaz veya geçerli yasaların açıkça izin verdiği durumlar dışında tersine mühendislik yapamazsın.',
        thirdTitle: '5. Reklam ve üçüncü taraf hizmetleri', thirdBody: 'Morph Jam üçüncü taraf uygulama mağazası, giriş, analitik, reklam ve barındırma hizmetleri kullanabilir. Bu tarafların kendi koşulları ve politikaları geçerli olabilir. Reklamların her zaman sunulacağı garanti edilmez. Kalıcı Reklamları Kaldır satın alımı, uygulamada açıklandığı şekilde zorunlu geçiş reklamlarını kapatır; isteğe bağlı ödüllü reklam seçeneklerini kaldırmaz.',
        ipTitle: '6. Fikri mülkiyet', ipBody: 'Kod, görseller, sesler, bulmacalar, level verileri, arayüz, marka ve belgeler dahil Morph Jam, NovaCode Dynamics Inc. veya lisans verenlerine aittir ve geçerli fikri mülkiyet yasalarıyla korunur.',
        updatesTitle: '7. Güncellemeler, kullanılabilirlik ve sona erdirme', updatesBody: 'Özellikleri ve içerikleri güncelleyebilir, dengeleyebilir, ekleyebilir, kaldırabilir veya sonlandırabiliriz. Çevrimiçi özellikler bakım, sağlayıcı arızası veya kontrolümüz dışındaki nedenlerle kullanılamayabilir. Hizmeti korumak, bu Koşulları uygulamak veya yasalara uymak için makul ölçüde gerekli olduğunda erişimi askıya alabiliriz. Uygulamayı kullanmayı bırakabilir ve verilerini istediğin zaman silebilirsin.',
        disclaimerTitle: '8. Sorumluluk reddi ve sınırlaması', disclaimerBody: 'Morph Jam “olduğu gibi” ve “mevcut olduğu ölçüde” sunulur. Yasaların izin verdiği azami ölçüde zımni garantileri reddeder, kesintisiz veya hatasız çalışma garantisi vermeyiz. Yasaların izin verdiği azami ölçüde NovaCode Dynamics Inc., uygulamadan doğan dolaylı, arızi, özel, sonuç olarak ortaya çıkan veya cezai kayıplardan sorumlu değildir. Bu Koşullardaki hiçbir hüküm, zorunlu tüketici hakları dahil yasal olarak hariç tutulamayacak hakları veya sorumlulukları ortadan kaldırmaz.',
        lawTitle: '9. Uygulanacak hukuk', lawBody: 'Bu Koşullar, ikamet ettiğin ülkedeki zorunlu tüketici korumaları dahil geçerli hukuka tabidir. Geçerli hukuk başka bir süreç gerektirmedikçe uyuşmazlıklar yasal yetkisi bulunan bir mahkemede görülmelidir.',
        contactTitle: '10. Değişiklikler ve iletişim', contactBody: 'Bu Koşulları güncelleyebiliriz. Güncelleme yapıldığında yukarıdaki yürürlük tarihi değişir ve önemli değişiklikler gerektiğinde bildirilir. Sorularını <a href="mailto:support@novacodedynamics.com?subject=Morph%20Jam%20Koşullar">support@novacodedynamics.com</a> adresine gönderebilirsin.',
        sideNav: '<strong>Bu sayfada</strong><a href="#eligibility">Uygunluk</a><a href="#license">Lisans</a><a href="#purchases">Satın alımlar</a><a href="#conduct">Kabul edilebilir kullanım</a><a href="#ip">Fikri mülkiyet</a><a href="#disclaimer">Sorumluluk</a><a href="#contact">İletişim</a>'
      },
      deleteAccount: {
        eyebrow: 'Hesap ve veriler', title: 'Morph Jam verilerini sil', lead: 'Misafir profilini veya bağlı hesabını doğrudan uygulama içinden kalıcı olarak silebilirsin.',
        stepsTitle: 'Uygulamadan silme', stepsBody: '<li><strong>Morph Jam</strong>’i aç ve <strong>Ayarlar</strong> bölümüne git.</li><li><strong>Hesap</strong> bölümünü aç.</li><li>Misafirsen <strong>Verilerimi Sil</strong>, giriş yaptıysan <strong>Hesabı Sil</strong> seçeneğini kullan.</li><li>Onay ekranındaki ilerleme ve öğeleri incele, ardından <strong>Kalıcı Olarak Sil</strong> seçeneğini seç.</li>',
        notice: '<strong>Bu işlem kalıcıdır.</strong> Kurtarma süresi yoktur. Uzak silme işlemi başarısız olursa güvenle yeniden deneyebilmen için Morph Jam yerel verileri olduğu gibi korur.',
        deletedTitle: 'Silinenler', deletedBody: '<ul><li>Misafir veya bağlı Morph Jam hesap verileri</li><li>Bulut kaydı ve yerel ilerleme</li><li>Tamamlanan levellar ve yıldızlar</li><li>Satın alınmış tüketilebilir coinler dahil coin bakiyesi</li><li>Günlük seri, oyun ayarları ve ders geçmişi</li><li>Hesap bağlantıları ve yerel kimlik doğrulama durumu</li></ul>',
        keptTitle: 'Silinmeyenler', keptBody: '<ul><li>Arayüzün beklenmedik biçimde dil değiştirmemesi için cihaz tercihi olarak kalan <strong>dil seçimi</strong>.</li><li>Apple veya Google mağaza hesabına ait olan ve geri yüklenebilen Reklamları Kaldır gibi <strong>kalıcı mağaza satın alımları</strong>.</li><li>Geçerli olduğu ölçüde yasal, güvenlik, işlem bütünlüğü veya dolandırıcılığı önleme yükümlülükleri nedeniyle saklanması gereken kayıtlar.</li></ul><p>İlgili coinler veya hesap verileri silindikten sonra tüketilebilir coin satın alımları geri yüklenemez.</p>',
        helpTitle: 'Uygulamaya erişemiyor musun?', helpBody: '<a href="mailto:support@novacodedynamics.com?subject=Morph%20Jam%20Hesap%20Silme">support@novacodedynamics.com</a> adresine e-posta gönder ve hesap silme desteğine ihtiyacın olduğunu belirt. Parola, Apple/Google giriş bilgileri veya ödeme kartı bilgisi gönderme. Talebi işlemeden önce hesabı doğrulamak için sınırlı bilgi isteyebiliriz.',
        sideNav: '<strong>Bu sayfada</strong><a href="#steps">Adımlar</a><a href="#deleted">Silinen veriler</a><a href="#kept">Korunan veriler</a><a href="#help">Yardım</a>'
      }
    },

    de: {
      meta: {
        home: ['Morph Jam — Formwandelnde Blockrätsel', 'Verschiebe Blöcke, verändere ihre Form und führe jedes Teil zum richtigen Tor.'],
        support: ['Morph Jam Support', 'Hilfe, häufige Fragen und Kontaktinformationen für Morph Jam.'],
        privacy: ['Morph Jam Datenschutzerklärung', 'Datenschutzerklärung für das mobile Spiel Morph Jam.'],
        terms: ['Morph Jam Nutzungsbedingungen', 'Nutzungsbedingungen für das mobile Spiel Morph Jam.'],
        deleteAccount: ['Morph Jam Konto löschen', 'So löschst du deine Morph Jam-Gastdaten oder dein verknüpftes Konto dauerhaft.']
      },
      nav: { home: 'Startseite', game: 'Das Spiel', screens: 'Screenshots', support: 'Support', privacy: 'Datenschutz', terms: 'Nutzungsbedingungen', deleteAccount: 'Konto löschen' },
      home: {
        eyebrow: 'Logikrätsel mit formwandelnden Blöcken', title: 'Schieben. Verwandeln. <span class="accent">Entkommen.</span>',
        lead: 'Blöcke bewegen sich nicht nur. Drehe, teile, strecke und verkleinere sie – und führe jede Form zum richtigen Ausgang.',
        discover: 'Morph Jam entdecken', getSupport: 'Support erhalten', availability: 'Demnächst für iPhone und Android',
        gameEyebrow: 'Ein Rätsel, das sich neu schreibt', gameTitle: 'Jeder Zug kann das Spielfeld verändern.', gameLead: 'Ein Block gleitet, bis ihn etwas stoppt. Der richtige Haltepunkt kann das Teil verwandeln – und deinen ganzen Plan.',
        shapeTitle: 'Form verändern', shapeBody: 'Drehe, strecke oder verkleinere Teile, damit sie zu den Toren passen und neue Wege entstehen.',
        splitTitle: 'Aufgabe teilen', splitBody: 'Ein geradzahliges Teil kann zu zwei getrennten Aufgaben mit eigenen Wegen und Ausgängen werden.',
        stepTitle: 'Einen Schritt Hilfe', stepBody: 'Wenn du feststeckst, berechnet Hilfe das aktuelle Spielfeld neu und zeigt einen sicheren Zug – nicht die ganze Lösung.',
        screensEyebrow: 'Ein Blick ins Spiel', screensTitle: 'Klare Regeln. Überraschende Folgen.', screen1: 'Teile bewegen sich nicht nur. Sie verändern ihre Form.', screen2: 'Teilen macht aus einem Teil zwei eigenständige Aufgaben.', screen3: 'Strecke, verkleinere und drehe, bis jedes Teil passt.'
      },
      support: {
        eyebrow: 'Support', title: 'Wie können wir helfen?', lead: 'Hier findest du die wichtigsten Informationen. Du kannst uns auch eine E-Mail senden.',
        emailTitle: 'E-Mail-Support', detailsTitle: 'Hilfreiche Angaben', detailsBody: 'Nenne dein Gerät, die Betriebssystemversion, die App-Version und die Levelnummer, damit wir das Problem schneller untersuchen können.',
        basicsTitle: 'So funktioniert das Rätsel', basicsBody: '<li>Wische einen Block in eine von vier Richtungen. Er gleitet, bis ihn eine Wand, ein Hindernis oder ein anderer Block stoppt.</li><li>Führe jeden Block durch ein Tor derselben Farbe. Ein nummeriertes Tor akzeptiert genau diese Größe; <strong>∞</strong> akzeptiert jede Größe.</li><li>Ein Drehen-, Teilen-, Strecken- oder Verkleinern-Feld wird nur aktiviert, wenn der Block seinen Zug darauf beendet.</li>',
        stuckTitle: 'Ich stecke in einem Level fest', stuckBody: 'Tippe im Spiel auf <strong>Hilfe</strong>. Das aktuelle Spielfeld wird geprüft und ein sicherer Richtungszug angezeigt. Die vollständige Lösung wird nicht verraten. Mit Rückgängig kannst du außerdem zu deiner letzten Entscheidung zurückkehren.',
        purchasesTitle: 'Kauf wiederherstellen', purchasesBody: 'Öffne den Shop im Spiel und wähle <strong>Käufe wiederherstellen</strong>. Dauerhafte Käufe wie „Keine Werbung“ sind mit deinem Apple- oder Google-Store-Konto verknüpft. Verbrauchte Münzpakete können nicht wiederhergestellt werden.',
        progressTitle: 'Problem mit Fortschritt oder Konto', progressBody: 'Morph Jam kann als Gast gespielt werden. Wenn du einen unterstützten Anmeldedienst verknüpft hast, verwende denselben Dienst, um synchronisierten Fortschritt wiederherzustellen. Wenn falscher Fortschritt angezeigt wird, spiele auf dem betroffenen Gerät nicht weiter und kontaktiere uns, bevor du Daten löschst.',
        adsTitle: 'Werbe- und Datenschutzeinstellungen', adsBody: 'Verfügbare Werbeeinwilligungen kannst du unter <strong>Einstellungen → Werbeoptionen</strong> prüfen oder ändern. Unter iOS lässt sich die Tracking-Berechtigung auch in den Systemeinstellungen ändern.',
        reportTitle: 'Fehler melden', reportBody: 'Schreibe an <a href="mailto:support@novacodedynamics.com?subject=Morph%20Jam%20Fehlerbericht">support@novacodedynamics.com</a>. Beschreibe, was du erwartet hast, was passiert ist und welche Aktion du zuletzt ausgeführt hast. Ein Screenshot ist hilfreich; sende niemals Passwörter oder Zahlungskartendaten.',
        sideNav: '<strong>Auf dieser Seite</strong><a href="#basics">Grundlagen</a><a href="#stuck">Festgefahren</a><a href="#purchases">Käufe</a><a href="#progress">Fortschritt</a><a href="#ads">Werbeoptionen</a><a href="#report">Fehler melden</a>'
      },
      privacy: {
        eyebrow: 'Rechtliches', title: 'Datenschutzerklärung', lead: 'Gültig ab 16. August 2026 · Morph Jam für iOS und Android',
        intro: 'Diese Datenschutzerklärung erläutert, wie <strong>NovaCode Dynamics Inc.</strong> („NovaCode Dynamics“, „wir“, „uns“) Informationen bei der Nutzung von Morph Jam verarbeitet. Fragen oder Datenschutzanfragen kannst du an <a href="mailto:support@novacodedynamics.com?subject=Morph%20Jam%20Datenschutz">support@novacodedynamics.com</a> senden.',
        collectTitle: '1. Informationen, die wir verarbeiten',
        collectBody: '<table><thead><tr><th>Kategorie</th><th>Beispiele und Zweck</th></tr></thead><tbody><tr><td>Installations- und Kontokennungen</td><td>Eine Gastinstallationskennung und, wenn du dich anmeldest, von Apple oder Google bereitgestellte Kennungen. Sie dienen dem Betrieb von Konten und der Synchronisierung des Fortschritts.</td></tr><tr><td>Spiel- und Speicherdaten</td><td>Abgeschlossene Level, Sterne, Münzen, Einstellungen, Hilfenutzung und ähnliche Fortschrittsdaten. Sie dienen dem Speichern, Synchronisieren und Verbessern des Spiels.</td></tr><tr><td>Kaufinformationen</td><td>Produkt-, Transaktions-, Kauf-Token- und Berechtigungsinformationen. Sie dienen der Kaufprüfung, verhindern doppelte Gutschriften und ermöglichen die Wiederherstellung geeigneter Produkte. Wir erhalten keine Zahlungskartendaten.</td></tr><tr><td>Analysen und Diagnosen</td><td>App-Version, Plattform, Sitzungs- und Levelereignisse, Abschlüsse, Neustarts, Hinweise, Rückgängig-Aktionen sowie Leistungs- oder Fehlerinformationen. Sie helfen uns, Zuverlässigkeit und Rätselschwierigkeit zu verstehen.</td></tr><tr><td>Werbe- und Einwilligungsdaten</td><td>Werbekennungen, soweit verfügbar, Einwilligungsstatus, Werbeanfragen und Interaktionen. Sie dienen der Auslieferung, Messung und Begrenzung von Werbung. Personalisierte Werbung wird nur verwendet, wenn sie zulässig ist und eine Einwilligung vorliegt.</td></tr><tr><td>Supportkommunikation</td><td>Deine E-Mail-Adresse und alle Informationen, die du bei einer Supportanfrage sendest.</td></tr></tbody></table><p>Wir fragen nicht nach genauem Standort, Kontakten, Fotos, Kamera- oder Mikrofoninhalten, Gesundheitsdaten oder Zahlungskartennummern.</p>',
        useTitle: '2. Verwendung von Informationen', useBody: '<ul><li>Bereitstellung des Spiels, des Gastzugangs, optionaler Konten, der Cloud-Speicherung, des Supports und der Kaufwiederherstellung.</li><li>Prüfung von Käufen, Schutz des Dienstes, Betrugsprävention und Fehlerdiagnose.</li><li>Messung der Spielleistung und Verbesserung von Levelbalance, Barrierefreiheit und Spielerlebnis.</li><li>Auslieferung und Messung von Werbung, einschließlich personalisierter Werbung nur bei entsprechender Erlaubnis.</li><li>Erfüllung gesetzlicher Pflichten und Beantwortung gültiger Betroffenenanfragen.</li></ul>',
        basisTitle: '3. Rechtsgrundlagen', basisBody: 'Soweit DSGVO, UK GDPR oder ähnliche Gesetze gelten, stützen wir uns auf die Vertragserfüllung für angeforderte Spiel- und Kontofunktionen, berechtigte Interessen am Betrieb, Schutz und der Verbesserung des Dienstes, Einwilligung für personalisierte Werbung oder Tracking, soweit erforderlich, sowie gesetzliche Pflichten. Eine Einwilligung kann über die Werbeoptionen im Spiel und die Geräteeinstellungen widerrufen werden.',
        shareTitle: '4. Dienstleister und Offenlegung', shareBody: '<p>Wir können Informationen mit Dienstleistern verarbeiten, die den Betrieb von Morph Jam unterstützen:</p><ul><li><strong>Apple</strong> und <strong>Google</strong> für App-Vertrieb, Anmeldung, Käufe, Einwilligungswerkzeuge und Werbedienste.</li><li><strong>GameAnalytics</strong> für Spielanalysen.</li><li><strong>Auf Railway gehostete Infrastruktur</strong> und unsere selbst gehosteten Nakama-Dienste für Konten, Cloud-Speicherstände, Levelbereitstellung und Kaufprüfung.</li></ul><p>Diese Anbieter verarbeiten Daten nach ihren eigenen Bedingungen und Datenschutzinformationen. Wir können Informationen außerdem offenlegen, wenn dies gesetzlich vorgeschrieben ist, zum Schutz von Nutzern oder des Dienstes oder im Rahmen einer Unternehmenstransaktion mit angemessenen Schutzmaßnahmen.</p><p>Wir verkaufen personenbezogene Daten nicht gegen Geld. Je nach Rechtsordnung kann personalisierte Werbung als „Weitergabe“ für kontextübergreifende verhaltensbezogene Werbung gelten; Einwilligungsoptionen und Geräteeinstellungen ermöglichen eine Begrenzung.</p>',
        retainTitle: '5. Speicherung und Sicherheit', retainBody: 'Spielkonto- und Cloud-Speicherdaten werden grundsätzlich aufbewahrt, solange das Konto oder Gastprofil aktiv ist, und über den Kontolöschvorgang gelöscht. Kauf-, Sicherheits-, Support- und Analysedaten können so lange gespeichert werden, wie dies für Betrugsprävention, Rechtskonformität, Streitbeilegung und dokumentierte Aufbewahrungspraktiken des jeweiligen Anbieters angemessen erforderlich ist. Wir setzen technische und organisatorische Schutzmaßnahmen ein; kein System kann jedoch absolute Sicherheit garantieren.',
        transferTitle: '6. Internationale Übermittlungen', transferBody: 'Unsere Anbieter können Informationen in anderen Ländern als deinem verarbeiten. Soweit erforderlich, nutzen wir anerkannte Übermittlungsmechanismen und Garantien der Anbieter, etwa Standardvertragsklauseln.',
        rightsTitle: '7. Deine Wahlmöglichkeiten und Rechte', rightsBody: '<ul><li>Du kannst als Gast spielen, ohne einen Drittanbieter für die Anmeldung zu verknüpfen.</li><li>Verfügbare Werbeeinwilligungen kannst du unter <strong>Einstellungen → Werbeoptionen</strong> und in den jeweiligen Geräteeinstellungen ändern.</li><li>Gastdaten oder dein Konto kannst du unter <strong>Einstellungen → Konto</strong> löschen. Siehe <a href="../delete-account/">Anleitung zur Kontolöschung</a>.</li><li>Soweit gesetzlich vorgesehen, kannst du Auskunft, Berichtigung, Löschung, Übertragbarkeit, Einschränkung, Widerspruch oder Widerruf der Einwilligung verlangen.</li></ul><p>Für die Ausübung eines Datenschutzrechts schreibe an <a href="mailto:support@novacodedynamics.com?subject=Morph%20Jam%20Datenschutzanfrage">support@novacodedynamics.com</a>. Wir müssen möglicherweise prüfen, ob die Anfrage dich betrifft.</p>',
        childrenTitle: '8. Kinder', childrenBody: 'Morph Jam richtet sich nicht an Kinder unter 13 Jahren, und wir erheben wissentlich keine personenbezogenen Daten von Kindern unter 13 Jahren. Wenn du glaubst, dass ein Kind Informationen bereitgestellt hat, kontaktiere uns, damit wir dies prüfen und sie gegebenenfalls löschen können.',
        changesTitle: '9. Änderungen und Kontakt', changesBody: 'Wir können diese Erklärung aktualisieren, wenn sich Morph Jam oder seine Anbieter ändern. Das oben genannte Datum wird angepasst; wesentliche Änderungen werden soweit erforderlich mitgeteilt.',
        sideNav: '<strong>Auf dieser Seite</strong><a href="#collect">Informationen</a><a href="#use">Verwendung</a><a href="#basis">Rechtsgrundlagen</a><a href="#share">Anbieter</a><a href="#retain">Speicherung</a><a href="#rights">Deine Rechte</a><a href="#children">Kinder</a>'
      },
      terms: {
        eyebrow: 'Rechtliches', title: 'Nutzungsbedingungen', lead: 'Gültig ab 16. August 2026 · Morph Jam für iOS und Android',
        intro: 'Diese Nutzungsbedingungen („Bedingungen“) regeln deine Nutzung von Morph Jam, bereitgestellt von <strong>NovaCode Dynamics Inc.</strong> Durch Herunterladen oder Nutzung von Morph Jam stimmst du diesen Bedingungen zu. Wenn du nicht zustimmst, darfst du die App nicht verwenden.',
        eligibilityTitle: '1. Berechtigung und Konten', eligibilityBody: 'Du musst rechtlich in der Lage sein, diesen Bedingungen zuzustimmen. Morph Jam richtet sich nicht an Kinder unter 13 Jahren. Du kannst als Gast spielen; die Verknüpfung eines unterstützten Anmeldedienstes ist optional. Du bist für Aktivitäten über dein verknüpftes Konto und für die Sicherheit deines Geräts und deiner Zugangsdaten verantwortlich.',
        licenseTitle: '2. Beschränkte Lizenz', licenseBody: 'Wir gewähren dir eine persönliche, beschränkte, nicht ausschließliche, nicht übertragbare und widerrufliche Lizenz, Morph Jam zu nicht kommerziellen Unterhaltungszwecken zu nutzen, vorbehaltlich dieser Bedingungen und der Regeln des Stores, aus dem du die App bezogen hast. Es werden keine Eigentumsrechte übertragen.',
        purchasesTitle: '3. Virtuelle Gegenstände und Käufe', purchasesBody: '<ul><li>Münzen und andere virtuelle Gegenstände haben keinen Geldwert, können nicht gegen Geld eingelöst und außerhalb ausdrücklich angebotener Funktionen nicht übertragen werden.</li><li>Käufe werden von Apple oder Google nach deren Zahlungs- und Erstattungsregeln abgewickelt. Wir erhalten keine Zahlungskartendaten.</li><li>Dauerhafte Käufe können über das Store-Konto wiederhergestellt werden, über das sie erworben wurden. Verbrauchte Münzpakete sind nicht wiederherstellbar.</li><li>Preise und Verfügbarkeit können je nach Store, Währung, Steuer und Region variieren.</li></ul>',
        conductTitle: '4. Zulässige Nutzung', conductBody: 'Du darfst Morph Jam oder verbundene Dienste nicht missbrauchen, andere Nutzer oder Infrastruktur stören, unbefugten Zugriff versuchen, Kauf- oder Werbesysteme ausnutzen, den Spielablauf zum Missbrauch von Diensten automatisieren, veränderte Kopien verbreiten oder die App zurückentwickeln, außer soweit geltendes Recht dies ausdrücklich erlaubt.',
        thirdTitle: '5. Werbung und Dienste Dritter', thirdBody: 'Morph Jam kann Dienste Dritter für App-Stores, Anmeldung, Analyse, Werbung und Hosting verwenden. Deren eigene Bedingungen und Richtlinien können gelten. Die Verfügbarkeit von Werbung ist nicht garantiert. Ein dauerhafter Kauf „Keine Werbung“ deaktiviert erzwungene Interstitial-Werbung wie in der App beschrieben, entfernt jedoch keine optionalen belohnten Werbeangebote.',
        ipTitle: '6. Geistiges Eigentum', ipBody: 'Morph Jam einschließlich Code, Grafiken, Audio, Rätseln, Leveldaten, Benutzeroberfläche, Marke und Dokumentation gehört NovaCode Dynamics Inc. oder seinen Lizenzgebern und ist durch geltende Gesetze zum geistigen Eigentum geschützt.',
        updatesTitle: '7. Updates, Verfügbarkeit und Beendigung', updatesBody: 'Wir können Funktionen und Inhalte aktualisieren, ausbalancieren, hinzufügen, entfernen oder einstellen. Onlinefunktionen können wegen Wartung, Ausfällen von Anbietern oder Umständen außerhalb unserer Kontrolle nicht verfügbar sein. Wir können den Zugang aussetzen, soweit dies zum Schutz des Dienstes, zur Durchsetzung dieser Bedingungen oder zur Einhaltung von Gesetzen angemessen erforderlich ist. Du kannst die App jederzeit nicht mehr nutzen und deine Daten löschen.',
        disclaimerTitle: '8. Haftungsausschluss und Haftungsbeschränkung', disclaimerBody: 'Morph Jam wird „wie besehen“ und „wie verfügbar“ bereitgestellt. Soweit gesetzlich zulässig, schließen wir stillschweigende Gewährleistungen aus und garantieren keinen ununterbrochenen oder fehlerfreien Betrieb. Soweit gesetzlich zulässig, haftet NovaCode Dynamics Inc. nicht für indirekte, beiläufige, besondere, Folge- oder Strafschäden aus der App. Nichts in diesen Bedingungen schließt Rechte oder Haftung aus, die gesetzlich nicht ausgeschlossen werden können, einschließlich zwingender Verbraucherrechte.',
        lawTitle: '9. Anwendbares Recht', lawBody: 'Diese Bedingungen unterliegen dem anwendbaren Recht einschließlich zwingender Verbraucherschutzvorschriften deines Wohnsitzlandes. Streitigkeiten sind vor einem rechtmäßig zuständigen Gericht zu führen, sofern das anwendbare Recht kein anderes Verfahren verlangt.',
        contactTitle: '10. Änderungen und Kontakt', contactBody: 'Wir können diese Bedingungen aktualisieren. Das oben genannte Datum ändert sich bei einer Aktualisierung; wesentliche Änderungen werden soweit erforderlich mitgeteilt. Fragen kannst du an <a href="mailto:support@novacodedynamics.com?subject=Morph%20Jam%20Bedingungen">support@novacodedynamics.com</a> senden.',
        sideNav: '<strong>Auf dieser Seite</strong><a href="#eligibility">Berechtigung</a><a href="#license">Lizenz</a><a href="#purchases">Käufe</a><a href="#conduct">Zulässige Nutzung</a><a href="#ip">Geistiges Eigentum</a><a href="#disclaimer">Haftung</a><a href="#contact">Kontakt</a>'
      },
      deleteAccount: {
        eyebrow: 'Konto und Daten', title: 'Morph Jam-Daten löschen', lead: 'Du kannst ein Gastprofil oder verknüpftes Konto direkt in der App dauerhaft löschen.',
        stepsTitle: 'In der App löschen', stepsBody: '<li>Öffne <strong>Morph Jam</strong> und gehe zu <strong>Einstellungen</strong>.</li><li>Öffne <strong>Konto</strong>.</li><li>Wähle als Gast <strong>Meine Daten löschen</strong> oder bei Anmeldung <strong>Konto löschen</strong>.</li><li>Prüfe den aufgeführten Fortschritt und die Gegenstände und wähle dann <strong>Dauerhaft löschen</strong>.</li>',
        notice: '<strong>Diese Aktion ist dauerhaft.</strong> Es gibt keine Wiederherstellungsfrist. Wenn die entfernte Löschung fehlschlägt, behält Morph Jam die lokalen Daten unverändert, damit du es sicher erneut versuchen kannst.',
        deletedTitle: 'Was gelöscht wird', deletedBody: '<ul><li>Gast- oder verknüpfte Morph Jam-Kontodaten</li><li>Cloud-Speicherstand und lokaler Fortschritt</li><li>Abgeschlossene Level und Sterne</li><li>Münzguthaben einschließlich gekaufter Verbrauchsmünzen</li><li>Tägliche Serie, Spieleinstellungen und Lektionsverlauf</li><li>Kontoverknüpfungen und lokaler Authentifizierungsstatus</li></ul>',
        keptTitle: 'Was nicht gelöscht wird', keptBody: '<ul><li>Die <strong>Spracheinstellung</strong>, die als Gerätepräferenz erhalten bleibt, damit sich die Sprache nicht unerwartet ändert.</li><li><strong>Dauerhafte Store-Käufe</strong> wie „Keine Werbung“, die zu deinem Apple- oder Google-Store-Konto gehören und wiederhergestellt werden können.</li><li>Daten, die aufgrund gesetzlicher, sicherheitsbezogener, transaktionsbezogener oder betrugspräventiver Pflichten aufbewahrt werden müssen.</li></ul><p>Verbrauchbare Münzkäufe können nach Löschung der zugehörigen Münzen oder Kontodaten nicht wiederhergestellt werden.</p>',
        helpTitle: 'Kein Zugriff auf die App?', helpBody: 'Sende eine E-Mail an <a href="mailto:support@novacodedynamics.com?subject=Morph%20Jam%20Kontoloeschung">support@novacodedynamics.com</a> und teile uns mit, dass du Hilfe bei der Kontolöschung brauchst. Sende keine Passwörter, Apple-/Google-Zugangsdaten oder Zahlungskartendaten. Vor der Bearbeitung können wir begrenzte Angaben zur Kontoprüfung anfordern.',
        sideNav: '<strong>Auf dieser Seite</strong><a href="#steps">Schritte</a><a href="#deleted">Gelöschte Daten</a><a href="#kept">Behaltene Daten</a><a href="#help">Hilfe</a>'
      }
    },

    es: {
      meta: {
        home: ['Morph Jam — Puzles de bloques cambiantes', 'Desliza bloques, cambia su forma y guía cada pieza hasta la puerta correcta.'],
        support: ['Soporte de Morph Jam', 'Ayuda, preguntas frecuentes e información de contacto de Morph Jam.'],
        privacy: ['Política de privacidad de Morph Jam', 'Política de privacidad del juego móvil Morph Jam.'],
        terms: ['Términos de uso de Morph Jam', 'Términos de uso del juego móvil Morph Jam.'],
        deleteAccount: ['Eliminar tu cuenta de Morph Jam', 'Cómo eliminar de forma permanente tus datos de invitado o tu cuenta vinculada de Morph Jam.']
      },
      nav: { home: 'Inicio', game: 'El juego', screens: 'Capturas', support: 'Soporte', privacy: 'Privacidad', terms: 'Términos', deleteAccount: 'Eliminar cuenta' },
      home: {
        eyebrow: 'Puzles lógicos con bloques cambiantes', title: 'Desliza. Transforma. <span class="accent">Escapa.</span>',
        lead: 'Los bloques hacen mucho más que moverse. Gíralos, divídelos, estíralos y encógelos; después lleva cada forma hasta la salida correcta.',
        discover: 'Descubre Morph Jam', getSupport: 'Obtener ayuda', availability: 'Próximamente en iPhone y Android',
        gameEyebrow: 'Un puzle que se reescribe', gameTitle: 'Cada movimiento puede cambiar el tablero.', gameLead: 'Un bloque sigue deslizándose hasta que algo lo detiene. El punto de parada correcto puede transformar la pieza y también tu plan.',
        shapeTitle: 'Cambia la forma', shapeBody: 'Gira, estira o encoge las piezas para ajustarlas a las puertas y abrir nuevas rutas.',
        splitTitle: 'Divide el problema', splitBody: 'Una pieza de longitud par puede convertirse en dos problemas independientes, cada uno con su ruta y salida.',
        stepTitle: 'Pide un solo paso', stepBody: 'Si te atascas, Ayuda vuelve a resolver el tablero actual y muestra un movimiento seguro, no la solución completa.',
        screensEyebrow: 'Dentro del juego', screensTitle: 'Reglas claras. Consecuencias sorprendentes.', screen1: 'Las piezas no solo se mueven: cambian de forma.', screen2: 'Dividir convierte una pieza en dos responsabilidades separadas.', screen3: 'Estira, encoge y gira hasta que cada pieza encaje.'
      },
      support: {
        eyebrow: 'Soporte', title: '¿Cómo podemos ayudarte?', lead: 'Consulta la información esencial o envíanos un correo electrónico.',
        emailTitle: 'Soporte por correo', detailsTitle: 'Datos útiles', detailsBody: 'Incluye tu dispositivo, versión del sistema operativo, versión de la aplicación y número de nivel para que podamos investigar más rápido.',
        basicsTitle: 'Cómo funciona el puzle', basicsBody: '<li>Desliza un bloque en una de las cuatro direcciones. Se mueve hasta que una pared, un obstáculo u otro bloque lo detiene.</li><li>Guía cada bloque por una puerta del mismo color. Una puerta numerada acepta exactamente ese tamaño; <strong>∞</strong> acepta cualquier tamaño.</li><li>Una casilla de Giro, División, Estiramiento o Reducción solo se activa cuando el bloque termina su movimiento sobre ella.</li>',
        stuckTitle: 'Estoy atascado en un nivel', stuckBody: 'Toca <strong>Ayuda</strong> dentro del juego. Comprobará el tablero actual y mostrará un movimiento direccional seguro, sin revelar la solución completa. También puedes usar Deshacer para volver a tu última decisión.',
        purchasesTitle: 'Restaurar una compra', purchasesBody: 'Abre la Tienda del juego y selecciona <strong>Restaurar compras</strong>. Las compras permanentes, como Sin anuncios, están vinculadas a tu cuenta de Apple o Google. Los paquetes de monedas consumidos no se pueden restaurar.',
        progressTitle: 'Problema de progreso o cuenta', progressBody: 'Puedes jugar a Morph Jam como invitado. Si vinculaste un proveedor de inicio de sesión compatible, usa el mismo proveedor para recuperar el progreso sincronizado. Si aparece un progreso incorrecto, deja de jugar en el dispositivo afectado y contacta con nosotros antes de eliminar datos.',
        adsTitle: 'Opciones de publicidad y privacidad', adsBody: 'Puedes revisar o cambiar las opciones de consentimiento publicitario en <strong>Ajustes → Opciones de anuncios</strong>. En iOS, el permiso de seguimiento también se puede cambiar en los ajustes del sistema.',
        reportTitle: 'Informar de un error', reportBody: 'Escribe a <a href="mailto:support@novacodedynamics.com?subject=Informe%20de%20error%20de%20Morph%20Jam">support@novacodedynamics.com</a>. Describe qué esperabas, qué ocurrió y cuál fue tu última acción. Una captura ayuda, pero nunca envíes contraseñas ni datos de tarjetas de pago.',
        sideNav: '<strong>En esta página</strong><a href="#basics">Conceptos básicos</a><a href="#stuck">Atascado</a><a href="#purchases">Compras</a><a href="#progress">Progreso</a><a href="#ads">Opciones de anuncios</a><a href="#report">Informar de un error</a>'
      },
      privacy: {
        eyebrow: 'Legal', title: 'Política de privacidad', lead: 'Vigente desde el 16 de agosto de 2026 · Morph Jam para iOS y Android',
        intro: 'Esta Política de privacidad explica cómo <strong>NovaCode Dynamics Inc.</strong> (“NovaCode Dynamics”, “nosotros”) trata la información cuando usas Morph Jam. Puedes enviar preguntas o solicitudes de privacidad a <a href="mailto:support@novacodedynamics.com?subject=Privacidad%20de%20Morph%20Jam">support@novacodedynamics.com</a>.',
        collectTitle: '1. Información que tratamos',
        collectBody: '<table><thead><tr><th>Categoría</th><th>Ejemplos y finalidad</th></tr></thead><tbody><tr><td>Identificadores de instalación y cuenta</td><td>Un identificador de instalación de invitado y, si decides iniciar sesión, identificadores proporcionados por Apple o Google. Se utilizan para gestionar cuentas y sincronizar el progreso.</td></tr><tr><td>Datos del juego y guardado</td><td>Niveles completados, estrellas, monedas, ajustes, uso de ayuda y datos similares de progreso. Se utilizan para guardar, sincronizar y mejorar el juego.</td></tr><tr><td>Información de compras</td><td>Producto, transacción, token de compra y derechos. Se utilizan para verificar compras, evitar créditos duplicados y restaurar productos válidos. No recibimos los datos de tu tarjeta de pago.</td></tr><tr><td>Análisis y diagnósticos</td><td>Versión de la aplicación, plataforma, eventos de sesión y nivel, finalizaciones, reinicios, pistas, deshacer y datos de rendimiento o errores. Se utilizan para entender la fiabilidad y dificultad de los puzles.</td></tr><tr><td>Datos de publicidad y consentimiento</td><td>Identificadores publicitarios cuando estén disponibles, estado del consentimiento, solicitudes e interacciones con anuncios. Se utilizan para mostrar, medir y limitar la publicidad. La publicidad personalizada solo se utiliza cuando esté permitida y exista consentimiento.</td></tr><tr><td>Comunicaciones de soporte</td><td>Tu dirección de correo y la información que envíes al pedir ayuda.</td></tr></tbody></table><p>No solicitamos ubicación precisa, contactos, fotos, contenido de cámara o micrófono, datos de salud ni números de tarjetas de pago.</p>',
        useTitle: '2. Cómo usamos la información', useBody: '<ul><li>Proporcionar el juego, acceso de invitado, cuentas opcionales, guardado en la nube, soporte y restauración de compras.</li><li>Verificar compras, proteger el servicio, prevenir fraude y diagnosticar fallos.</li><li>Medir el rendimiento y mejorar el equilibrio de niveles, accesibilidad y experiencia del jugador.</li><li>Mostrar y medir publicidad, incluida publicidad personalizada solo cuando los permisos aplicables lo permitan.</li><li>Cumplir obligaciones legales y responder a solicitudes válidas de derechos.</li></ul>',
        basisTitle: '3. Bases jurídicas', basisBody: 'Cuando sean aplicables el RGPD, el RGPD del Reino Unido o leyes similares, nos basamos en la ejecución del contrato para ofrecer funciones solicitadas del juego y la cuenta; intereses legítimos para operar, proteger y mejorar el servicio; consentimiento para publicidad personalizada o seguimiento cuando se requiera; y obligaciones legales. Puedes retirar el consentimiento mediante las opciones publicitarias de la aplicación y los ajustes del dispositivo.',
        shareTitle: '4. Proveedores de servicios y divulgación', shareBody: '<p>Podemos tratar información con proveedores que ayudan a operar Morph Jam:</p><ul><li><strong>Apple</strong> y <strong>Google</strong> para distribución, inicio de sesión, compras, herramientas de consentimiento y publicidad.</li><li><strong>GameAnalytics</strong> para análisis del juego.</li><li><strong>Infraestructura alojada en Railway</strong> y nuestros servicios Nakama autogestionados para cuentas, guardados en la nube, entrega de niveles y verificación de compras.</li></ul><p>Estos proveedores tratan datos según sus propias condiciones y documentación de privacidad. También podemos divulgar información cuando lo exija la ley, para proteger a usuarios o al servicio, o como parte de una operación empresarial con garantías adecuadas.</p><p>No vendemos información personal a cambio de dinero. Según tu jurisdicción, la publicidad personalizada puede considerarse “compartir” datos para publicidad conductual entre contextos; los controles de consentimiento y ajustes del dispositivo permiten limitarla.</p>',
        retainTitle: '5. Conservación y seguridad', retainBody: 'La información de la cuenta y del guardado en la nube se conserva generalmente mientras la cuenta o perfil de invitado esté activo y se elimina mediante el proceso de eliminación de cuenta. Los registros de compras, seguridad, soporte y análisis pueden conservarse durante el tiempo razonablemente necesario para prevenir fraude, cumplir la ley, resolver disputas y seguir las prácticas documentadas del proveedor correspondiente. Aplicamos medidas técnicas y organizativas, pero ningún sistema garantiza seguridad absoluta.',
        transferTitle: '6. Transferencias internacionales', transferBody: 'Nuestros proveedores pueden tratar información en países distintos del tuyo. Cuando sea necesario, utilizamos mecanismos de transferencia reconocidos y garantías de los proveedores, como cláusulas contractuales tipo.',
        rightsTitle: '7. Tus opciones y derechos', rightsBody: '<ul><li>Puedes jugar como invitado sin vincular un proveedor externo de inicio de sesión.</li><li>Puedes cambiar las opciones de consentimiento publicitario en <strong>Ajustes → Opciones de anuncios</strong> y en los ajustes relevantes del dispositivo.</li><li>Puedes eliminar tus datos de invitado o cuenta desde <strong>Ajustes → Cuenta</strong>. Consulta la <a href="../delete-account/">guía de eliminación de cuenta</a>.</li><li>Puedes solicitar acceso, rectificación, supresión, portabilidad, limitación, oposición o retirada del consentimiento cuando la ley te otorgue estos derechos.</li></ul><p>Para ejercer un derecho de privacidad, escribe a <a href="mailto:support@novacodedynamics.com?subject=Solicitud%20de%20privacidad%20de%20Morph%20Jam">support@novacodedynamics.com</a>. Es posible que debamos verificar que la solicitud se refiere a ti.</p>',
        childrenTitle: '8. Menores', childrenBody: 'Morph Jam no está dirigido a menores de 13 años y no recopilamos conscientemente información personal de menores de 13 años. Si crees que un menor ha proporcionado información, contacta con nosotros para que podamos investigarlo y eliminarla cuando corresponda.',
        changesTitle: '9. Cambios y contacto', changesBody: 'Podemos actualizar esta política cuando cambien Morph Jam o sus proveedores. Se modificará la fecha de vigencia y se comunicarán los cambios importantes cuando sea necesario.',
        sideNav: '<strong>En esta página</strong><a href="#collect">Información</a><a href="#use">Uso</a><a href="#basis">Bases jurídicas</a><a href="#share">Proveedores</a><a href="#retain">Conservación</a><a href="#rights">Tus derechos</a><a href="#children">Menores</a>'
      },
      terms: {
        eyebrow: 'Legal', title: 'Términos de uso', lead: 'Vigentes desde el 16 de agosto de 2026 · Morph Jam para iOS y Android',
        intro: 'Estos Términos de uso (“Términos”) regulan tu uso de Morph Jam, ofrecido por <strong>NovaCode Dynamics Inc.</strong> Al descargar o usar Morph Jam aceptas estos Términos. Si no estás de acuerdo, no uses la aplicación.',
        eligibilityTitle: '1. Requisitos y cuentas', eligibilityBody: 'Debes tener capacidad legal para aceptar estos Términos. Morph Jam no está dirigido a menores de 13 años. Puedes jugar como invitado; vincular un proveedor de inicio de sesión compatible es opcional. Eres responsable de la actividad realizada mediante tu cuenta vinculada y de mantener seguros tu dispositivo y credenciales.',
        licenseTitle: '2. Licencia limitada', licenseBody: 'Te concedemos una licencia personal, limitada, no exclusiva, intransferible y revocable para usar Morph Jam con fines de entretenimiento no comercial, sujeta a estos Términos y a las normas de la tienda donde lo obtuviste. No se te transfiere ningún derecho de propiedad.',
        purchasesTitle: '3. Objetos virtuales y compras', purchasesBody: '<ul><li>Las monedas y otros objetos virtuales no tienen valor en efectivo, no pueden canjearse por dinero ni transferirse fuera de las funciones que proporcionemos expresamente.</li><li>Apple o Google procesan las compras según sus políticas de pago y reembolso. No recibimos los datos de tu tarjeta.</li><li>Las compras permanentes pueden restaurarse con la cuenta de la tienda que las adquirió. Los paquetes de monedas consumidos no se pueden restaurar.</li><li>Los precios y la disponibilidad pueden variar según la tienda, moneda, impuestos y región.</li></ul>',
        conductTitle: '4. Uso aceptable', conductBody: 'No puedes hacer un uso indebido de Morph Jam o sus servicios, interferir con otros usuarios o la infraestructura, intentar accesos no autorizados, explotar sistemas de compra o publicidad, automatizar el juego para abusar de servicios, distribuir copias modificadas ni aplicar ingeniería inversa, salvo cuando la ley aplicable lo permita expresamente.',
        thirdTitle: '5. Publicidad y servicios de terceros', thirdBody: 'Morph Jam puede utilizar servicios externos de tienda, inicio de sesión, análisis, publicidad y alojamiento. Pueden aplicarse sus propios términos y políticas. No se garantiza la disponibilidad de anuncios. Una compra permanente Sin anuncios desactiva la publicidad intersticial forzada según se describe en la aplicación, pero no elimina las opciones voluntarias de anuncios con recompensa.',
        ipTitle: '6. Propiedad intelectual', ipBody: 'Morph Jam, incluido su código, arte, audio, puzles, datos de niveles, interfaz, marca y documentación, pertenece a NovaCode Dynamics Inc. o a sus licenciantes y está protegido por las leyes aplicables de propiedad intelectual.',
        updatesTitle: '7. Actualizaciones, disponibilidad y terminación', updatesBody: 'Podemos actualizar, equilibrar, añadir, eliminar o interrumpir funciones y contenido. Las funciones en línea pueden no estar disponibles por mantenimiento, fallos de proveedores o circunstancias fuera de nuestro control. Podemos suspender el acceso cuando sea razonablemente necesario para proteger el servicio, aplicar estos Términos o cumplir la ley. Puedes dejar de usar la aplicación y eliminar tus datos en cualquier momento.',
        disclaimerTitle: '8. Exclusiones y limitación de responsabilidad', disclaimerBody: 'Morph Jam se ofrece “tal cual” y “según disponibilidad”. En la máxima medida permitida por la ley, rechazamos garantías implícitas y no garantizamos un funcionamiento ininterrumpido o sin errores. En la máxima medida permitida, NovaCode Dynamics Inc. no responderá por pérdidas indirectas, incidentales, especiales, consecuentes o punitivas derivadas de la aplicación. Nada excluye derechos o responsabilidades que legalmente no puedan excluirse, incluidos derechos obligatorios del consumidor.',
        lawTitle: '9. Legislación aplicable', lawBody: 'Estos Términos se rigen por la legislación aplicable, incluidas las protecciones obligatorias al consumidor de tu país de residencia. Cualquier disputa deberá plantearse ante un tribunal con jurisdicción legal, salvo que la ley exija otro proceso.',
        contactTitle: '10. Cambios y contacto', contactBody: 'Podemos actualizar estos Términos. La fecha de vigencia cambiará y los cambios importantes se comunicarán cuando sea necesario. Puedes enviar preguntas a <a href="mailto:support@novacodedynamics.com?subject=Terminos%20de%20Morph%20Jam">support@novacodedynamics.com</a>.',
        sideNav: '<strong>En esta página</strong><a href="#eligibility">Requisitos</a><a href="#license">Licencia</a><a href="#purchases">Compras</a><a href="#conduct">Uso aceptable</a><a href="#ip">Propiedad intelectual</a><a href="#disclaimer">Responsabilidad</a><a href="#contact">Contacto</a>'
      },
      deleteAccount: {
        eyebrow: 'Cuenta y datos', title: 'Eliminar tus datos de Morph Jam', lead: 'Puedes eliminar de forma permanente un perfil de invitado o una cuenta vinculada directamente desde la aplicación.',
        stepsTitle: 'Eliminar desde la aplicación', stepsBody: '<li>Abre <strong>Morph Jam</strong> y ve a <strong>Ajustes</strong>.</li><li>Abre <strong>Cuenta</strong>.</li><li>Selecciona <strong>Eliminar mis datos</strong> como invitado o <strong>Eliminar cuenta</strong> si has iniciado sesión.</li><li>Revisa el progreso y los objetos de la pantalla de confirmación y selecciona <strong>Eliminar permanentemente</strong>.</li>',
        notice: '<strong>Esta acción es permanente.</strong> No existe periodo de recuperación. Si falla la eliminación remota, Morph Jam conserva intactos los datos locales para que puedas volver a intentarlo de forma segura.',
        deletedTitle: 'Qué se elimina', deletedBody: '<ul><li>Datos de invitado o de la cuenta vinculada de Morph Jam</li><li>Guardado en la nube y progreso local</li><li>Niveles completados y estrellas</li><li>Saldo de monedas, incluidas monedas consumibles compradas</li><li>Racha diaria, ajustes del juego e historial de lecciones</li><li>Vínculos de cuenta y estado local de autenticación</li></ul>',
        keptTitle: 'Qué no se elimina', keptBody: '<ul><li>La <strong>preferencia de idioma</strong>, que permanece como ajuste del dispositivo para evitar cambios inesperados.</li><li>Las <strong>compras permanentes de la tienda</strong>, como Sin anuncios, que pertenecen a tu cuenta de Apple o Google y pueden restaurarse.</li><li>Registros que deban conservarse por obligaciones legales, de seguridad, integridad de transacciones o prevención del fraude.</li></ul><p>Las compras de monedas consumibles no se pueden restaurar después de eliminar las monedas o los datos de cuenta relacionados.</p>',
        helpTitle: '¿No puedes acceder a la aplicación?', helpBody: 'Envía un correo a <a href="mailto:support@novacodedynamics.com?subject=Eliminacion%20de%20cuenta%20de%20Morph%20Jam">support@novacodedynamics.com</a> e indica que necesitas ayuda para eliminar la cuenta. No envíes contraseñas, credenciales de Apple/Google ni datos de tarjetas. Podemos solicitar información limitada para verificar la cuenta antes de tramitar la solicitud.',
        sideNav: '<strong>En esta página</strong><a href="#steps">Pasos</a><a href="#deleted">Datos eliminados</a><a href="#kept">Datos conservados</a><a href="#help">Ayuda</a>'
      }
    },

    fr: {
      meta: {
        home: ['Morph Jam — Casse-têtes de blocs transformables', 'Faites glisser les blocs, transformez-les et guidez chaque pièce vers la bonne porte.'],
        support: ['Assistance Morph Jam', 'Aide, questions fréquentes et coordonnées pour Morph Jam.'],
        privacy: ['Politique de confidentialité de Morph Jam', 'Politique de confidentialité du jeu mobile Morph Jam.'],
        terms: ["Conditions d’utilisation de Morph Jam", "Conditions d’utilisation du jeu mobile Morph Jam."],
        deleteAccount: ['Supprimer votre compte Morph Jam', 'Comment supprimer définitivement vos données invité ou votre compte Morph Jam associé.']
      },
      nav: { home: 'Accueil', game: 'Le jeu', screens: 'Captures', support: 'Assistance', privacy: 'Confidentialité', terms: 'Conditions', deleteAccount: 'Supprimer le compte' },
      home: {
        eyebrow: 'Casse-têtes logiques de blocs transformables', title: 'Glissez. Transformez. <span class="accent">Échappez-vous.</span>',
        lead: 'Les blocs ne font pas que bouger. Faites-les pivoter, divisez-les, étirez-les et rétrécissez-les, puis guidez chaque forme vers la bonne sortie.',
        discover: 'Découvrir Morph Jam', getSupport: 'Obtenir de l’aide', availability: 'Bientôt sur iPhone et Android',
        gameEyebrow: 'Un casse-tête qui se réécrit', gameTitle: 'Chaque mouvement peut changer le plateau.', gameLead: 'Un bloc continue de glisser jusqu’à ce qu’un obstacle l’arrête. Le bon point d’arrêt peut transformer la pièce et tout votre plan.',
        shapeTitle: 'Changez la forme', shapeBody: 'Faites pivoter, étirez ou rétrécissez les pièces pour les adapter aux portes et ouvrir de nouveaux chemins.',
        splitTitle: 'Divisez le problème', splitBody: 'Une pièce de longueur paire peut devenir deux problèmes indépendants, chacun avec son chemin et sa sortie.',
        stepTitle: 'Demandez une étape', stepBody: 'Si vous êtes bloqué, l’Aide recalcule le plateau actuel et montre un mouvement sûr, pas la solution complète.',
        screensEyebrow: 'Dans le jeu', screensTitle: 'Des règles claires. Des conséquences surprenantes.', screen1: 'Les pièces ne font pas que bouger : elles changent de forme.', screen2: 'La division transforme une pièce en deux responsabilités distinctes.', screen3: 'Étirez, rétrécissez et faites pivoter jusqu’à ce que chaque pièce trouve sa place.'
      },
      support: {
        eyebrow: 'Assistance', title: 'Comment pouvons-nous vous aider ?', lead: 'Consultez les informations essentielles ci-dessous ou envoyez-nous un e-mail.',
        emailTitle: 'Assistance par e-mail', detailsTitle: 'Informations utiles', detailsBody: 'Indiquez votre appareil, la version du système, la version de l’application et le numéro du niveau afin que nous puissions enquêter plus rapidement.',
        basicsTitle: 'Fonctionnement du casse-tête', basicsBody: '<li>Faites glisser un bloc dans l’une des quatre directions. Il avance jusqu’à ce qu’un mur, un obstacle ou un autre bloc l’arrête.</li><li>Guidez chaque bloc vers une porte de la même couleur. Une porte numérotée accepte exactement cette taille ; <strong>∞</strong> accepte toutes les tailles.</li><li>Une case Rotation, Division, Étirement ou Réduction ne s’active que si le bloc termine son mouvement dessus.</li>',
        stuckTitle: 'Je suis bloqué dans un niveau', stuckBody: 'Touchez <strong>Aide</strong> dans le jeu. Le plateau actuel est analysé et un mouvement sûr est affiché sans révéler la solution complète. Vous pouvez aussi utiliser Annuler pour revenir sur votre dernière décision.',
        purchasesTitle: 'Restaurer un achat', purchasesBody: 'Ouvrez la Boutique du jeu et choisissez <strong>Restaurer les achats</strong>. Les achats permanents, comme Sans publicité, sont liés à votre compte Apple ou Google. Les lots de pièces consommés ne peuvent pas être restaurés.',
        progressTitle: 'Problème de progression ou de compte', progressBody: 'Morph Jam peut être joué en tant qu’invité. Si vous avez associé un fournisseur de connexion pris en charge, utilisez le même pour récupérer la progression synchronisée. Si une progression incorrecte apparaît, arrêtez de jouer sur l’appareil concerné et contactez-nous avant de supprimer des données.',
        adsTitle: 'Choix publicitaires et confidentialité', adsBody: 'Vous pouvez consulter ou modifier les consentements publicitaires dans <strong>Réglages → Choix publicitaires</strong>. Sur iOS, l’autorisation de suivi peut aussi être modifiée dans les réglages du système.',
        reportTitle: 'Signaler un bug', reportBody: 'Écrivez à <a href="mailto:support@novacodedynamics.com?subject=Signalement%20de%20bug%20Morph%20Jam">support@novacodedynamics.com</a>. Décrivez le résultat attendu, ce qui s’est produit et votre dernière action. Une capture d’écran est utile, mais n’envoyez jamais de mot de passe ni de données de carte de paiement.',
        sideNav: '<strong>Sur cette page</strong><a href="#basics">Principes du jeu</a><a href="#stuck">Bloqué</a><a href="#purchases">Achats</a><a href="#progress">Progression</a><a href="#ads">Choix publicitaires</a><a href="#report">Signaler un bug</a>'
      },
      privacy: {
        eyebrow: 'Informations légales', title: 'Politique de confidentialité', lead: 'En vigueur depuis le 16 août 2026 · Morph Jam pour iOS et Android',
        intro: 'Cette Politique de confidentialité explique comment <strong>NovaCode Dynamics Inc.</strong> (« NovaCode Dynamics », « nous ») traite les informations lorsque vous utilisez Morph Jam. Vous pouvez envoyer vos questions ou demandes relatives à la confidentialité à <a href="mailto:support@novacodedynamics.com?subject=Confidentialite%20Morph%20Jam">support@novacodedynamics.com</a>.',
        collectTitle: '1. Informations que nous traitons',
        collectBody: '<table><thead><tr><th>Catégorie</th><th>Exemples et finalité</th></tr></thead><tbody><tr><td>Identifiants d’installation et de compte</td><td>Un identifiant d’installation invité et, si vous choisissez de vous connecter, des identifiants fournis par Apple ou Google. Ils servent à gérer les comptes et synchroniser la progression.</td></tr><tr><td>Données de jeu et de sauvegarde</td><td>Niveaux terminés, étoiles, pièces, réglages, utilisation de l’aide et autres données de progression. Elles servent à sauvegarder, synchroniser et améliorer le jeu.</td></tr><tr><td>Informations d’achat</td><td>Produit, transaction, jeton d’achat et droits. Ils servent à vérifier les achats, éviter les crédits en double et restaurer les produits admissibles. Nous ne recevons pas les données de votre carte de paiement.</td></tr><tr><td>Analyses et diagnostics</td><td>Version de l’application, plateforme, événements de session et de niveau, fins de niveau, redémarrages, indices, annulations, performances et erreurs. Ils servent à comprendre la fiabilité et la difficulté des casse-têtes.</td></tr><tr><td>Données publicitaires et de consentement</td><td>Identifiants publicitaires lorsqu’ils sont disponibles, état du consentement, demandes et interactions publicitaires. Ils servent à diffuser, mesurer et limiter la publicité. La publicité personnalisée n’est utilisée que lorsqu’elle est autorisée et acceptée.</td></tr><tr><td>Communications avec l’assistance</td><td>Votre adresse e-mail et les informations envoyées lorsque vous demandez de l’aide.</td></tr></tbody></table><p>Nous ne demandons pas votre position précise, vos contacts, vos photos, du contenu de caméra ou microphone, des données de santé ou des numéros de carte de paiement.</p>',
        useTitle: '2. Utilisation des informations', useBody: '<ul><li>Fournir le jeu, l’accès invité, les comptes facultatifs, la sauvegarde cloud, l’assistance et la restauration des achats.</li><li>Vérifier les achats, sécuriser le service, prévenir la fraude et diagnostiquer les problèmes.</li><li>Mesurer les performances et améliorer l’équilibre des niveaux, l’accessibilité et l’expérience des joueurs.</li><li>Diffuser et mesurer la publicité, y compris la publicité personnalisée uniquement lorsque les autorisations applicables le permettent.</li><li>Respecter les obligations légales et répondre aux demandes valides relatives aux droits.</li></ul>',
        basisTitle: '3. Bases juridiques', basisBody: 'Lorsque le RGPD, le RGPD britannique ou des lois similaires s’appliquent, nous nous appuyons sur l’exécution du contrat pour fournir les fonctions de jeu et de compte demandées, nos intérêts légitimes à exploiter, sécuriser et améliorer le service, le consentement pour la publicité personnalisée ou le suivi lorsque nécessaire, et nos obligations légales. Vous pouvez retirer votre consentement via les choix publicitaires de l’application et les réglages de l’appareil.',
        shareTitle: '4. Prestataires et divulgation', shareBody: '<p>Nous pouvons traiter des informations avec des prestataires qui contribuent au fonctionnement de Morph Jam :</p><ul><li><strong>Apple</strong> et <strong>Google</strong> pour la distribution, la connexion, les achats, les outils de consentement et la publicité.</li><li><strong>GameAnalytics</strong> pour l’analyse du jeu.</li><li><strong>Infrastructure hébergée sur Railway</strong> et nos services Nakama auto-hébergés pour les comptes, sauvegardes cloud, distribution des niveaux et vérification des achats.</li></ul><p>Ces prestataires traitent les données selon leurs propres conditions et documents de confidentialité. Nous pouvons également divulguer des informations lorsque la loi l’exige, pour protéger les utilisateurs ou le service, ou dans le cadre d’une opération commerciale assortie de garanties appropriées.</p><p>Nous ne vendons pas les informations personnelles contre de l’argent. Selon votre juridiction, la publicité personnalisée peut être considérée comme un « partage » pour la publicité comportementale intercontextuelle ; les contrôles de consentement et réglages de l’appareil permettent de la limiter.</p>',
        retainTitle: '5. Conservation et sécurité', retainBody: 'Les informations de compte et de sauvegarde cloud sont généralement conservées tant que le compte ou profil invité reste actif, puis supprimées via le processus de suppression de compte. Les données d’achat, de sécurité, d’assistance et d’analyse peuvent être conservées pendant la durée raisonnablement nécessaire à la prévention de la fraude, au respect de la loi, au règlement des litiges et aux pratiques documentées du prestataire concerné. Nous appliquons des mesures techniques et organisationnelles, mais aucun système ne garantit une sécurité absolue.',
        transferTitle: '6. Transferts internationaux', transferBody: 'Nos prestataires peuvent traiter des informations dans d’autres pays que le vôtre. Lorsque nécessaire, nous utilisons des mécanismes de transfert reconnus et les garanties des prestataires, comme les clauses contractuelles types.',
        rightsTitle: '7. Vos choix et vos droits', rightsBody: '<ul><li>Vous pouvez jouer en tant qu’invité sans associer de fournisseur de connexion tiers.</li><li>Vous pouvez modifier les consentements publicitaires disponibles dans <strong>Réglages → Choix publicitaires</strong> et dans les réglages concernés de l’appareil.</li><li>Vous pouvez supprimer vos données invité ou votre compte depuis <strong>Réglages → Compte</strong>. Consultez le <a href="../delete-account/">guide de suppression du compte</a>.</li><li>Vous pouvez demander l’accès, la rectification, la suppression, la portabilité, la limitation, l’opposition ou le retrait du consentement lorsque la loi vous accorde ces droits.</li></ul><p>Pour exercer un droit, écrivez à <a href="mailto:support@novacodedynamics.com?subject=Demande%20de%20confidentialite%20Morph%20Jam">support@novacodedynamics.com</a>. Nous pouvons devoir vérifier que la demande vous concerne.</p>',
        childrenTitle: '8. Enfants', childrenBody: 'Morph Jam ne s’adresse pas aux enfants de moins de 13 ans et nous ne recueillons pas sciemment leurs informations personnelles. Si vous pensez qu’un enfant a fourni des informations, contactez-nous afin que nous puissions enquêter et les supprimer lorsque nécessaire.',
        changesTitle: '9. Modifications et contact', changesBody: 'Nous pouvons mettre cette politique à jour lorsque Morph Jam ou ses prestataires évoluent. La date d’entrée en vigueur sera modifiée et les changements importants seront communiqués lorsque nécessaire.',
        sideNav: '<strong>Sur cette page</strong><a href="#collect">Informations</a><a href="#use">Utilisation</a><a href="#basis">Bases juridiques</a><a href="#share">Prestataires</a><a href="#retain">Conservation</a><a href="#rights">Vos droits</a><a href="#children">Enfants</a>'
      },
      terms: {
        eyebrow: 'Informations légales', title: 'Conditions d’utilisation', lead: 'En vigueur depuis le 16 août 2026 · Morph Jam pour iOS et Android',
        intro: 'Les présentes Conditions d’utilisation (« Conditions ») régissent votre utilisation de Morph Jam, fourni par <strong>NovaCode Dynamics Inc.</strong> En téléchargeant ou en utilisant Morph Jam, vous acceptez ces Conditions. Si vous ne les acceptez pas, n’utilisez pas l’application.',
        eligibilityTitle: '1. Admissibilité et comptes', eligibilityBody: 'Vous devez avoir la capacité juridique d’accepter ces Conditions. Morph Jam ne s’adresse pas aux enfants de moins de 13 ans. Vous pouvez jouer en tant qu’invité ; l’association d’un fournisseur de connexion compatible est facultative. Vous êtes responsable de l’activité via votre compte associé et de la sécurité de votre appareil et de vos identifiants.',
        licenseTitle: '2. Licence limitée', licenseBody: 'Nous vous accordons une licence personnelle, limitée, non exclusive, non transférable et révocable pour utiliser Morph Jam à des fins de divertissement non commercial, sous réserve de ces Conditions et des règles de la boutique où vous l’avez obtenu. Aucun droit de propriété ne vous est transféré.',
        purchasesTitle: '3. Objets virtuels et achats', purchasesBody: '<ul><li>Les pièces et autres objets virtuels n’ont aucune valeur monétaire, ne peuvent pas être échangés contre de l’argent et ne peuvent pas être transférés en dehors des fonctions que nous proposons expressément.</li><li>Les achats sont traités par Apple ou Google selon leurs politiques de paiement et de remboursement. Nous ne recevons pas les données de votre carte.</li><li>Les achats permanents peuvent être restaurés via le compte de boutique qui les a acquis. Les lots de pièces consommés ne peuvent pas être restaurés.</li><li>Les prix et la disponibilité peuvent varier selon la boutique, la devise, les taxes et la région.</li></ul>',
        conductTitle: '4. Utilisation acceptable', conductBody: 'Vous ne pouvez pas utiliser Morph Jam ou ses services de manière abusive, perturber d’autres utilisateurs ou l’infrastructure, tenter un accès non autorisé, exploiter les systèmes d’achat ou de publicité, automatiser le jeu pour abuser des services, distribuer des copies modifiées ou effectuer de l’ingénierie inverse, sauf si la loi applicable l’autorise expressément.',
        thirdTitle: '5. Publicité et services tiers', thirdBody: 'Morph Jam peut utiliser des services tiers de boutique, connexion, analyse, publicité et hébergement. Leurs conditions et politiques peuvent s’appliquer. La disponibilité des publicités n’est pas garantie. Un achat permanent Sans publicité désactive les publicités interstitielles forcées comme indiqué dans l’application, mais ne supprime pas les choix facultatifs de publicités récompensées.',
        ipTitle: '6. Propriété intellectuelle', ipBody: 'Morph Jam, notamment son code, ses graphismes, son audio, ses casse-têtes, ses données de niveaux, son interface, sa marque et sa documentation, appartient à NovaCode Dynamics Inc. ou à ses concédants et est protégé par les lois applicables sur la propriété intellectuelle.',
        updatesTitle: '7. Mises à jour, disponibilité et résiliation', updatesBody: 'Nous pouvons mettre à jour, équilibrer, ajouter, supprimer ou interrompre des fonctions et du contenu. Les fonctions en ligne peuvent être indisponibles pour maintenance, défaillance d’un prestataire ou circonstances hors de notre contrôle. Nous pouvons suspendre l’accès lorsque cela est raisonnablement nécessaire pour protéger le service, appliquer ces Conditions ou respecter la loi. Vous pouvez cesser d’utiliser l’application et supprimer vos données à tout moment.',
        disclaimerTitle: '8. Exclusions et limitation de responsabilité', disclaimerBody: 'Morph Jam est fourni « en l’état » et « selon disponibilité ». Dans toute la mesure permise par la loi, nous excluons les garanties implicites et ne garantissons pas un fonctionnement ininterrompu ou sans erreur. Dans toute la mesure permise, NovaCode Dynamics Inc. n’est pas responsable des pertes indirectes, accessoires, spéciales, consécutives ou punitives liées à l’application. Rien n’exclut les droits ou responsabilités qui ne peuvent légalement l’être, notamment les droits impératifs des consommateurs.',
        lawTitle: '9. Droit applicable', lawBody: 'Ces Conditions sont régies par le droit applicable, notamment les protections impératives des consommateurs de votre pays de résidence. Tout litige doit être porté devant un tribunal légalement compétent, sauf si la loi applicable impose une autre procédure.',
        contactTitle: '10. Modifications et contact', contactBody: 'Nous pouvons mettre ces Conditions à jour. La date d’entrée en vigueur changera et les modifications importantes seront communiquées lorsque nécessaire. Vous pouvez envoyer vos questions à <a href="mailto:support@novacodedynamics.com?subject=Conditions%20Morph%20Jam">support@novacodedynamics.com</a>.',
        sideNav: '<strong>Sur cette page</strong><a href="#eligibility">Admissibilité</a><a href="#license">Licence</a><a href="#purchases">Achats</a><a href="#conduct">Utilisation acceptable</a><a href="#ip">Propriété intellectuelle</a><a href="#disclaimer">Responsabilité</a><a href="#contact">Contact</a>'
      },
      deleteAccount: {
        eyebrow: 'Compte et données', title: 'Supprimer vos données Morph Jam', lead: 'Vous pouvez supprimer définitivement un profil invité ou un compte associé directement dans l’application.',
        stepsTitle: 'Supprimer depuis l’application', stepsBody: '<li>Ouvrez <strong>Morph Jam</strong> et accédez aux <strong>Réglages</strong>.</li><li>Ouvrez <strong>Compte</strong>.</li><li>Choisissez <strong>Supprimer mes données</strong> en tant qu’invité ou <strong>Supprimer le compte</strong> si vous êtes connecté.</li><li>Vérifiez la progression et les objets indiqués sur l’écran de confirmation, puis choisissez <strong>Supprimer définitivement</strong>.</li>',
        notice: '<strong>Cette action est définitive.</strong> Il n’existe aucun délai de récupération. Si la suppression distante échoue, Morph Jam conserve les données locales afin que vous puissiez réessayer sans risque.',
        deletedTitle: 'Ce qui est supprimé', deletedBody: '<ul><li>Données invité ou du compte Morph Jam associé</li><li>Sauvegarde cloud et progression locale</li><li>Niveaux terminés et étoiles</li><li>Solde de pièces, y compris les pièces consommables achetées</li><li>Série quotidienne, réglages du jeu et historique des leçons</li><li>Associations de compte et état d’authentification local</li></ul>',
        keptTitle: 'Ce qui n’est pas supprimé', keptBody: '<ul><li>La <strong>préférence de langue</strong>, conservée sur l’appareil afin d’éviter un changement inattendu de langue.</li><li>Les <strong>achats permanents</strong>, comme Sans publicité, liés à votre compte Apple ou Google et pouvant être restaurés.</li><li>Les données devant être conservées pour des obligations légales, de sécurité, d’intégrité des transactions ou de prévention de la fraude.</li></ul><p>Les achats de pièces consommables ne peuvent pas être restaurés après la suppression des pièces ou données de compte associées.</p>',
        helpTitle: 'Impossible d’accéder à l’application ?', helpBody: 'Envoyez un e-mail à <a href="mailto:support@novacodedynamics.com?subject=Suppression%20de%20compte%20Morph%20Jam">support@novacodedynamics.com</a> en précisant que vous avez besoin d’aide pour supprimer votre compte. N’envoyez pas de mots de passe, d’identifiants Apple/Google ou de données de carte. Nous pouvons demander des informations limitées pour vérifier le compte avant de traiter la demande.',
        sideNav: '<strong>Sur cette page</strong><a href="#steps">Étapes</a><a href="#deleted">Données supprimées</a><a href="#kept">Données conservées</a><a href="#help">Aide</a>'
      }
    }
  };

  function detectLanguage() {
    const preferences = Array.isArray(navigator.languages) && navigator.languages.length
      ? navigator.languages
      : [navigator.language || 'en'];

    for (const preference of preferences) {
      const language = String(preference).toLowerCase().split('-')[0];
      if (SUPPORTED_LANGUAGES.includes(language)) return language;
    }

    return 'en';
  }

  function getValue(source, path) {
    return path.split('.').reduce((value, key) => value && value[key], source);
  }

  const language = detectLanguage();
  const page = document.body.dataset.page;
  document.documentElement.lang = language;

  if (language === 'en') return;

  const translations = copy[language];
  document.querySelectorAll('[data-i18n]').forEach((element) => {
    const value = getValue(translations, element.dataset.i18n);
    if (typeof value === 'string') element.textContent = value;
  });

  document.querySelectorAll('[data-i18n-html]').forEach((element) => {
    const value = getValue(translations, element.dataset.i18nHtml);
    if (typeof value === 'string') element.innerHTML = value;
  });

  const meta = translations.meta && translations.meta[page];
  if (meta) {
    document.title = meta[0];
    const description = document.querySelector('meta[name="description"]');
    if (description) description.setAttribute('content', meta[1]);
  }
})();
